management:
  endpoint:
    env:
      show-values: ALWAYS

supportedCountriesCode:
  - CN
  - MO
  - DK
  - AB
supportedCountriesCodePrefix:
  - CN00
  - MO00
  - HK00
legacyCountryCodes: [PH]
hello: remoteHello
serverName: ${nginx.server.name}
